### ISSUE TITLE
Example ldap: no attribute source

### ISSUE THREAD

**Issue by tobiasBora** [salt-formulas/salt-formula-gitlab#6]
Hello,

First, thanks for the formula! However, the given ldap example fails:

```
minion:
    Data failed to compile:
----------
    Rendering SLS 'base:gitlab.server.service' failed: Jinja variable 'dict object' has no attribute 'source'

``` 
I guess that one should add a source, from git I guess?

**Comment by fpytloun** [comment]
See `metadata/service/server/single.yml`
It should be:
```
source:
  engine: pkg
```

or to install from source:
```
source:
  engine: src
  address: some git url
```

for this option, see `server/_service_src.sls`

But this should be formula default defined in map.jinja. I'm going to fix it.
